### ISSUE TITLE
Quest accept problem

### ISSUE THREAD

**Issue by alexaltex** [ebodziony/gladiatus-script#2]
The script can no longer auto-accept quests.

**Comment by ebodziony** [comment]
Fixed. I'm not sure how long this will work, because script is using icon names to recognize the type of quest. Hovewer icon names was changed from meaningfull names, like "icon_arena_inactive", to strings like "00f1a594723515a77dcd6d66c918fb".
I assigned them manually, but if icon names will change again, I will need to try different approach.
